[package]
name = "alligator"
version = "0.1.0"
license = "MIT"
keywords= ["async", "futures", "main"]
categories = ["asynchronous"]
readme = "README.md"
repository = "https://github.com/gpace1/alligator/"
description = "Alligator is for getting the output value from a future"
